# Traefik dynamic config: forward duckiesays.com to k8s nginx ingress
# Mount this file into /etc/traefik/dynamic/ on the NAS
http:
  services:
    duckiesays-k8s-svc:
      loadbalancer:
        servers:
          - url: "https://172.30.249.1:31571"
        passHostHeader: true
      serversTransport: duckiesays-transport

    duckiesays-legacy-k8s-svc:
      loadbalancer:
        servers:
          - url: "https://172.30.249.1:31571"
        passHostHeader: true
      serversTransport: duckiesays-transport

  serversTransports:
    duckiesays-transport:
      insecureSkipVerify: true
