# Traefik dynamic config: forward duckiesays.com to k8s nginx ingress
# Mount this file into /etc/traefik/dynamic/ on the NAS
http:
  services:
    duckiesays-k8s-svc:
      loadbalancer:
        servers:
          - url: "http://172.30.249.1:30248"
        passHostHeader: true
