version: "3.7"

services:
  ###### ----- Media related ----- ######
  overseerr:
    image: lscr.io/linuxserver/overseerr:develop
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
      - UMASK=002
    ports:
      - 5055:5055
    volumes:
      - /volume2/docker-configs/overseerr/app/config:/config
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entryPoints=zt-web"
      - "traefik.http.routers.overseerr.rule=Host(`requests.zt.not-really.me`)" 
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=5055"
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=organizr
      - UMASK=002
    volumes:
      - /volume2/docker-configs/sonarr/data:/config
      - /volume1/plex-media:/plex-media
      - /volume2/docker-configs/downloads:/downloads
    ports:
      - 7878:7878
      - 8989:8989
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entryPoints=zt-web"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.zt.not-really.me`)" 
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - /volume2/docker-configs/radarr/data:/config
      - /volume1/plex-media:/plex-media
      - /volume2/docker-configs/downloads:/downloads
    ports:
      - 7676:7878
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entryPoints=zt-web"
      - "traefik.http.routers.radarr.rule=Host(`radarr.zt.not-really.me`)" 
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - /volume2/docker-configs/prowlarr/data:/config
    ports:
      - 9696:9696
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entryPoints=zt-web"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.zt.not-really.me`)" 
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    restart: unless-stopped
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - /volume2/docker-configs/sabnzbd/config:/config
      - /volume2/docker-configs/downloads:/downloads
    ports:
      - 9000:9000
    networks:
      - traefik-public
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '3' # Use 3 of 4 cores
          memory: '4g' # Support large article cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.entryPoints=zt-web"
      - "traefik.http.routers.sabnzbd.rule=Host(`sab.zt.not-really.me`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=9000"

    restart: unless-stopped

###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge
