# Core services like proxy, watchtower, status.
version: "3.7"

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    network_mode: host
    labels:
      - traefik.enable=true
      - "--providers.docker.allowEmptyServices=true" # Enable allowEmptyServices
      - "--entrypoints.websecure.http.tls.domains[0].main=not-really.me"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.not-really.me"
      - "--entrypoints.websecure.http.tls.domains[1].main=duckiesays.com"
      - "--entrypoints.websecure.http.tls.domains[1].sans=*.duckiesays.com"
    volumes:
      - /volume2/docker-configs/traefik/:/etc/traefik/
      - /volume2/docker-configs/traefik/logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 28800 --cleanup
    restart: unless-stopped

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    networks:
      - traefik-public
    volumes:
      - /volume2/docker-configs/adguard/work:/opt/adguardhome/work
      - /volume2/docker-configs/adguard/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"  # DoT
      
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.zt.not-really.me`)"  # Adjust subdomain as needed
      - "traefik.http.routers.adguard.entrypoints=zt-web"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"  # Use 3000 for initial setup, then change to 80


###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge
