# Core services like proxy, watchtower, status.
version: "3.7"

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 172.31.250.200:8080:8080/tcp #Dash disabled so we can have rr.not-really.me
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - "--providers.docker.allowEmptyServices=true" # Enable allowEmptyServices
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.http.tls.domains[0].main=not-really.me"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.not-really.me"
      - "--entrypoints.websecure.http.tls.domains[1].main=duckiesays.com"
      - "--entrypoints.websecure.http.tls.domains[1].sans=*.duckiesays.com"
    networks:
      - traefik-public
    volumes:
      - /volume2/docker-configs/traefik/:/etc/traefik/
      - /volume2/docker-configs/traefik/logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 28800 --cleanup
    restart: unless-stopped

# HA is going to end up being a "core service" eventually, I suppose. 
#  homeassistant:
#    container_name: homeassistant
#    image: "ghcr.io/home-assistant/home-assistant:stable"
#    volumes:
#      - /volume2/docker-configs/ha-config:/config
#      - /etc/localtime:/etc/localtime:ro
#      - /run/dbus:/run/dbus:ro
#    restart: unless-stopped
#    privileged: true
#    network_mode: host


###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge
