# Core services like proxy, homepage, status, and search.
version: "3.7"

services:
  traefik:
    image: traefik:v2.5.1
    container_name: traefik
    ports:
      - 80:80/tcp
      - 443:443/tcp
    #  - 172.31.250.200:8080:8080/tcp # disabled due to rr bug
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - "--entrypoints.websecure.http.tls.domains[0].main=not-really.me"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.not-really.me"
    networks:
      - traefik-public
    volumes:
      - /volume1/arrs/traefik/:/etc/traefik/
      - /volume1/arrs/traefik/logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 2000:2000
    volumes:
      - /volume1/arrs/homepage/config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - PORT=2000
      - TZ=America/New_York
    networks:
      - traefik-public
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entryPoints=websecure"
      - "traefik.http.routers.homepage.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.homepage.rule=Host(`not-really.me`,`www.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.homepage.loadbalancer.server.port=2000"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=2000"
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /volume1/arrs/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 3001:3001
    depends_on:
      - traefik
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime_kuma.entryPoints=websecure"
      - "traefik.http.routers.uptime_kuma.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.uptime_kuma.rule=Host(`status.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=3001"
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - 1234:1234
    volumes:
      - /volume1/arrs/searxng:/etc/searxng:rw
    environment:
      - PUID=1024
      - PGID=100
      - TZ=America/New_York
      - SEARXNG_BASE_URL=https://search.not-really.me/
      - SEARXNG_PORT=1234
      - BIND_ADDRESS=0.0.0.0:1234
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - traefik
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.entryPoints=websecure"
      - "traefik.http.routers.search.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.search.rule=Host(`search.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.search.loadbalancer.server.port=1234"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=1234"
    restart: unless-stopped

###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge
