services:
  quake3-server:
    image: heyvaldemar/quake3-server:latest
    volumes:
      - /volume2/docker-configs/quake3/server.cfg:/quakejs/base/baseq3/server.cfg
    environment:
      SERVER: 0.0.0.0
    ports:
      - "8080:80"
      - "27960:27960"
    restart: unless-stopped
