# All the other services
version: "3.7"

services:
    quakejs:
        container_name: quakejs
        ports:
            - 80:8080
            - 27960:27960
        image: 'treyyoder/quakejs:latest'
