version: '2'
services:
    quakejs:
        container_name: quakejs
        environment:
            - HTTP_PORT=8080
        ports:
            - '8080:80'
            - '27960:27960'
        volumes:
            - /quakejs/base/baseq3:/volume2/docker-configs/quakejs
        image: 'treyyoder/quakejs:latest'
