version: '3.8'

services:
  quakejs:
    container_name: quakejs
    ports:
      - '10080:80'
      - '27960:27960'
    image: 'treyyoder/quakejs:latest'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quakejs.entryPoints=web"
      - "traefik.http.routers.quakejs.rule=Host(`quake.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.routers.quakejs.priority=1000" # Higher priority to override global redirect
      - "traefik.http.routers.quakejs.tls=false"
      - "traefik.http.services.quakejs.loadbalancer.server.port=10080"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=10080"
    restart: unless-stopped
