version: '3.8'

services:
  ioquake3:
    image: ghcr.io/neonwatty/quakejs-https:latest
    container_name: quakejs-https
    ports:
      - "27960:27960/udp"
      - "9029:8080"
    environment:
      GAME_PARAMS: "+set dedicated 1 +set sv_allowDownload 1 +set com_hunkmegs 64"
      IOQ3_PORT: "27960"
      Q3_MAP: "q3dm17"
      DL_URL_PR: "https://files.ioquake3.org/Linux.zip"
      DL_URL_PATCH: "https://files.ioquake3.org/quake3-latest-pk3s.zip"
      UID: "1024"
      GID: "100"
      UMASK: "000"
      DATA_PERM: "770"
      LEGACY_PROTOCOL: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.entryPoints=websecure"
      - "traefik.http.routers.search.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.search.rule=Host(`quake.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.search.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"
    volumes:
      - /volume2/docker-configs/ioquake3:/ioquake3
    restart: unless-stopped
