# All the other services
version: "3.7"

services:
    quakejs:
        container_name: quakejs
        environment:
            - HTTP_PORT=8080
        networks:
            - traefik-public
        ports:
            - '8080:80'
            - '27960:27960'
        image: 'treyyoder/quakejs:latest'


###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge
