version: '3.8'

services:
  quakejs:
    container_name: quakejs
    environment:
      - HTTP_PORT=10080
    ports:
      - '10080:80'
      - '27960:27960'
    image: 'treyyoder/quakejs:latest'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.entryPoints=web"
      - "traefik.http.routers.search.rule=Host(`quake.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.search.loadbalancer.server.port=10080"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=10080"
    restart: unless-stopped
