version: '3.7'
services:
  justin-page:
    build:
      context: ./justin-page
      dockerfile: Dockerfile
    container_name: justin-page
    networks:
    - traefik-public
    labels:
    - traefik.enable=true
    - traefik.http.routers.justin-page.entrypoints=websecure
    - traefik.http.routers.justin-page.tls.certresolver=letsEncrypt
    - traefik.http.routers.justin-page.rule=Host(`justin.not-really.me`)
    - traefik.http.services.justin-page.loadbalancer.server.port=80
    - traefik.docker.network=traefik-public
    restart: unless-stopped
networks:
  traefik-public: {}