version: '3.8'

volumes:
  n8n_storage:
environment:
  - N8N_HOST=https://n8n.not-really.me
  - N8N_PROTOCOL=https
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entryPoints=websecure"
      - "traefik.http.routers.n8n.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.n8n.rule=Host(`n8n.not-really.me`)" 
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=5678"
    volumes:
      - n8n_storage:/home/node/.n8n
    
networks:
  traefik-public:
    external: true
    driver: bridge
