version: "3.7"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - VERSION=docker
      - UMASK=002
    volumes:
      - /volume2/docker-configs/plex-confg:/config
      - /volume1/plex-media:/plex-media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - /volume2/docker-configs/tautulli/config:/config
    ports:
      - 8181:8181
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tau.entryPoints=zt-web"
      - "traefik.http.routers.tau.rule=Host(`tau.zt.not-really.me`)" 
      - "traefik.http.services.tau.loadbalancer.server.port=8181"
    restart: unless-stopped

  ersatztv:
    image: ghcr.io/ersatztv/ersatztv
    container_name: ersatztv
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - /volume2/docker-configs/ersatztv:/config
      - /volume1/plex-media:/plex-media:ro
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8409:8409
    networks:
      - traefik-public
    tmpfs:
      - /transcode
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ersatz.entryPoints=zt-web"
      - "traefik.http.routers.ersatz.rule=Host(`tv.zt.not-really.me`)"
      - "traefik.http.services.ersatz.loadbalancer.server.port=8409"
    restart: unless-stopped

###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge
