version: "3.7"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - VERSION=docker
      - UMASK=002
    volumes:
      - /volume2/docker-configs/plex-confg:/config
      - /volume1/plex-media:/plex-media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - /volume2/docker-configs/tautulli/config:/config
    ports:
      - 8181:8181
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tau.entryPoints=websecure"
      - "traefik.http.routers.tau.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.tau.rule=Host(`tau.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.tau.loadbalancer.server.port=8181"
    restart: unless-stopped

###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge
