# All the other services
version: "3.7"

services:
  
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 2000:2000
    volumes:
      - /volume2/docker-configs/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      - PORT=2000
      - TZ=America/New_York
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entryPoints=websecure"
      - "traefik.http.routers.homepage.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.homepage.rule=Host(`not-really.me`)" 
      - "traefik.http.services.homepage.loadbalancer.server.port=2000"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=2000"
    restart: unless-stopped

  rickroll:
    image: modem7/docker-rickroll
    container_name: Rickroll
    ports:
      - 1987:8080
    environment:
      - TITLE="not-really-roll" # Changes the title of the webpage
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rr.entryPoints=websecure"
      - "traefik.http.routers.rr.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.rr.rule=Host(`rr.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.rr.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-public"
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    ports:
      - 1234:8080
    volumes:
      - /volume2/docker-configs/searxng:/etc/searxng:rw
    environment:
      - PUID=1024
      - PGID=100
      - TZ=America/New_York
      - SEARXNG_BASE_URL=https://search.not-really.me/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      test: ["NONE"]
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.entryPoints=websecure"
      - "traefik.http.routers.search.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.search.rule=Host(`search.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.search.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-public"
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: sync.not-really.me
    environment:
      - PUID=1024
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /volume2/docker-configs/syncthing/config:/config
      - /volume1:/volume1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sync.entryPoints=websecure"
      - "traefik.http.routers.sync.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.sync.rule=Host(`sync.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.sync.loadbalancer.server.port=8384"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=8384"
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1024
      - PGID=100
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /volume2/docker-configs/calibre-web/config:/config
      - /volume1/files/books/:/books
    networks:
      - traefik-public
    ports:
      - 8083:8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.books.entryPoints=websecure"
      - "traefik.http.routers.books.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.books.rule=Host(`books.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.books.loadbalancer.server.port=8083"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=8083"
    restart: unless-stopped


  utfodem:
    image: cadeon924/utfodem:latest
    container_name: utfodem
    networks:
      - traefik-public
    ports:
      - 12345:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.utfodem.entryPoints=websecure"
      - "traefik.http.routers.utfodem.tls.certResolver=letsEncrypt"
      - "traefik.http.routers.utfodem.rule=Host(`cypher.not-really.me`)" # Edit here to change the domain name
      - "traefik.http.services.utfodem.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-public"
    restart: unless-stopped

  duckiesays:
    image: cadeon924/duckiesays:latest
    container_name: duckiesays
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duckiesays.entrypoints=websecure"
      - "traefik.http.routers.duckiesays.tls.certresolver=letsencrypt"
      - "traefik.http.routers.duckiesays.tls.domains[0].main=duckiesays.com"
      - "traefik.http.routers.duckiesays.tls.domains[0].sans=*.duckiesays.com"
      - "traefik.http.routers.duckiesays.rule=HostRegexp(`legacy.duckiesays.com`)"
      - "traefik.http.services.duckiesays.loadbalancer.server.port=7007"
      - "traefik.docker.network=traefik-public"
    restart: unless-stopped

###### ----- Docker control ----- ######
networks:
  traefik-public:
    external: true
    driver: bridge

volumes:
  postgresdata:
