apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
  - namespace.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - configmap.yaml
  - kubeconfig-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
