apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusters/infra
  - clusters/steam/namespace.yaml
  - clusters/steam/deployment.yaml
  - clusters/steam/service.yaml
  - clusters/steam/ingress.yaml

namespace: steam
