serversTransport:
  maxIdleConnsPerHost: -1
  forwardingTimeouts:
    responseHeaderTimeout: 0s

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: "/etc/traefik/routes/"
    watch: true

api:
  insecure: true
  dashboard: true

entryPoints:
  # HTTP → redirect to HTTPS
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  # HTTPS — all services
  # Exposure controlled by DNS, not by entrypoint
  websecure:
    address: ":443"

certificatesResolvers:
  letsEncrypt:
    acme:
      storage: /etc/traefik/acme.json
      email: cadeon924@gmail.com
      dnsChallenge:
        provider: digitalocean
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

accessLog:
  filePath: "/var/log/access.log"
  bufferingSize: 2000

log:
  level: DEBUG
