apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: echo-admin
  namespace: echo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: echo-admin
subjects:
  - kind: ServiceAccount
    name: echo
    namespace: echo
